package jku.se.Controller;

import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import jku.se.*;
import jku.se.repository.InvoiceRepository;
import jku.se.repository.UserRepository;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AdminInvoiceManagementController {
    private static final Logger LOGGER = Logger.getLogger(AdminInvoiceManagementController.class.getName());

    @FXML private ComboBox<Invoice> selectInvoice;
    @FXML private ComboBox<String> selectUser;
    @FXML private TextField amountField;
    @FXML private TextField reimbursementField;
    @FXML private DatePicker invoiceDateField;
    @FXML private ComboBox<String> categoryCombobox;
    @FXML private Button changeButton;
    @FXML private Button invoiceAcceptButton;
    @FXML private Button declinedButton;
    @FXML private Button deleteButton1;
    @FXML private Label statusLabel;

    @FXML
    public void initialize() {
        List<String> emails = UserRepository.getAllUserEmails();
        selectUser.setItems(FXCollections.observableArrayList(emails));
        selectUser.setOnAction(e -> {
            searchInvoice(new ActionEvent());
        });
        //generated by ai
        //load details of invoice
        selectInvoice.setOnAction(e -> {
            Invoice selectedInvoice = selectInvoice.getValue();
            if (selectedInvoice != null) {
                amountField.setText(String.valueOf(selectedInvoice.getAmount()));
                reimbursementField.setText(String.valueOf(selectedInvoice.getReimbursement()));
                invoiceDateField.setValue(selectedInvoice.getDate());
                categoryCombobox.setValue(selectedInvoice.getCategory().name());
            }
            categoryCombobox.setItems(FXCollections.observableArrayList(
                    "SUPERMARKET", "RESTAURANT"
            ));
        });
    }

    //choice user - current user are not in
    @FXML
    private void searchUser(ActionEvent event) throws IOException {
        List<String> emails = UserRepository.getAllUsersWithoutLoggedAdmin(UserDashboardController.getCurrentUserEmail());

        selectUser.setItems(FXCollections.observableArrayList(emails));
    }

    @FXML
    //choice invoice from user
    private void searchInvoice(ActionEvent event) {
        String selectedUserEmail = selectUser.getValue();
        if (LOGGER.isLoggable(Level.INFO)) {
            LOGGER.info("Selected user email: " + selectedUserEmail); // Debug
        }

        if (selectedUserEmail == null || selectedUserEmail.isEmpty()) {
            showAlert(Alert.AlertType.ERROR, "User Error", "Please select an user first.");
            return;
        }

        List<Invoice> invoices = InvoiceRepository.getAllInvoicesUser(selectedUserEmail);

        selectInvoice.setItems(FXCollections.observableArrayList(invoices));
    }

    //is changed when you press the change button
    @FXML
    private void changeInvoiceDetails(ActionEvent event) {

        Invoice selectedInvoice = selectInvoice.getValue();

        if (selectedInvoice == null) {
            showAlert(Alert.AlertType.ERROR, "Validation Error", "Please select an invoice to update.");
            return;
        }
        //save old and new date for changing date
        LocalDate oldDate = selectedInvoice.getDate();

        //check if invoice is in current month
        LocalDate now = LocalDate.now();
        if(!selectedInvoice.isInCurrentMonth(oldDate, now)){
            showAlert(Alert.AlertType.ERROR, "Validation Error", "The invoice can no longer be changed - only possible in the current month!");
            return;
        }

        if (selectedInvoice != null) {
            try {
                double newAmount = Double.parseDouble(amountField.getText());
                String newCategory = categoryCombobox.getValue();
                LocalDate newDate = invoiceDateField.getValue();

                if (!selectedInvoice.isValidAmount(newAmount)) {
                    showAlert(Alert.AlertType.ERROR, "Validation Error", "Amount must be greater than 0 and less than 1000!");
                    return;
                }

                selectedInvoice.setAmount(newAmount);
                selectedInvoice.setCategory(Category.valueOf(newCategory));

                if(!selectedInvoice.isDateOnWeekday(newDate)){
                    showAlert(Alert.AlertType.ERROR, "Validation Error", "Invoice date must be a weekday!");
                    return;
                }
                // Check if date changed - AI generated
                if (!newDate.equals(oldDate)) {
                    try (Connection con = DatabaseConnection.getConnection()) {
                        boolean exists = InvoiceRepository.invoiceExists(con, selectedInvoice.getUserEmail(), java.sql.Date.valueOf(newDate));
                        if (exists) {
                            showAlert(Alert.AlertType.ERROR, "Validation Error", "An invoice already exists for this user on the selected date.");
                            return;
                        }
                    } catch (SQLException e) {

                        showAlert(Alert.AlertType.ERROR, "Database Error", "Database error: " + e.getMessage());
                        return;
                    }
                }
                selectedInvoice.setDate(newDate);
                selectedInvoice.setStatus(Status.PROCESSING);  // after update invoice details set status to processing

                //after changing category or amount - change reimbursement
                double newReimbursement = selectedInvoice.calculateRefund();
                selectedInvoice.setReimbursement(newReimbursement);

                InvoiceRepository.updateInvoiceAmount(selectedInvoice);
                InvoiceRepository.updateInvoiceCategory(selectedInvoice);
                InvoiceRepository.updateInvoiceDate(selectedInvoice);
                InvoiceRepository.updateInvoiceStatus(selectedInvoice);
                InvoiceRepository.updateInvoiceReimbursement(selectedInvoice);
                showAlert(Alert.AlertType.INFORMATION, "Success", "Invoice updated successfully.");


                //Update data output in JAVAFX
                amountField.setText(String.valueOf(selectedInvoice.getAmount()));
                reimbursementField.setText(String.valueOf(selectedInvoice.getReimbursement()));
                invoiceDateField.setValue(selectedInvoice.getDate());
                categoryCombobox.setValue(selectedInvoice.getCategory().name());
            } catch (Exception e) {
                showAlert(Alert.AlertType.ERROR, "Update Error", "Update failed: " + e.getMessage());

            }
        }

    }
    //accept invoice update db
    @FXML
    private void handleAcceptInvoice(ActionEvent event) throws SQLException {
        Invoice selectedInvoice = selectInvoice.getValue();

        if (selectedInvoice != null) {
            selectedInvoice.setStatus(Status.APPROVED);
            InvoiceRepository.updateInvoiceStatus(selectedInvoice);
            UserRepository.getByEmail(selectedInvoice.getUserEmail());
            new Notification("Your invoice from " + selectedInvoice.getCreatedAtString() + " was approved.");
            showAlert(Alert.AlertType.INFORMATION, "Success", "Invoice accepted successfully.");

        }
    }

    //declined invoice update db
    @FXML
    private void handleDeclinedInvoice(ActionEvent event) throws SQLException {
        Invoice selectedInvoice = selectInvoice.getValue();

        if (selectedInvoice != null) {
            selectedInvoice.setStatus(Status.DECLINED);
            InvoiceRepository.updateInvoiceStatus(selectedInvoice);
            UserRepository.getByEmail(selectedInvoice.getUserEmail());
            new Notification("Your invoice from " + selectedInvoice.getCreatedAtString() + " was rejected.");
            showAlert(Alert.AlertType.WARNING, "Invoice Declined", "Invoice was declined.");

        }
    }

    //Admin can delete a invoice from a user
    @FXML
    private void handleDeleteInvoice(ActionEvent event) throws SQLException{
        Invoice selectedInvoice = selectInvoice.getValue();

        if (selectedInvoice != null) {
            InvoiceRepository.deleteInvoice(selectedInvoice);
            showAlert(Alert.AlertType.INFORMATION, "Invoice Deleted", "Invoice was deleted.");

        }
    }


    @FXML
    private void cancelEditAdmin(ActionEvent event) throws IOException {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/dashboard2.fxml"));
            Scene scene = new Scene(loader.load());

            Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();

            stage.setScene(scene);
            stage.show();
    }
    //add alerts for information
    private void showAlert(Alert.AlertType type, String title, String message) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}


